### PR TITLE
Removed deprecated methods

### PR DESCRIPTION
**Pull request by Nickanda**
.sendEmbed is a deprecated method, updated to .send

### CODE REVIEW

**Comment by SunburntRock89** [comment]
huh, didn't notice those

**Comment by austinhuang0131** [comment]
that's not actually how you do it but i'll fix further

**Comment by SunburntRock89** [comment]
yep exactly

**Comment by austinhuang0131** [comment]
[this is how you do it](https://github.com/austinhuang0131/discordtel/blob/rewrite/commands/help.js)

**Pull request merged**
