### PR TITLE
TS-ify config

### PR DESCRIPTION
**Pull request by Rexogamer**

### CODE REVIEW

**Comment by Mitchell3514** [comment]
Can you splice it up, as in:
Export colors
Export links
Export settings
Export values
Etc

**Comment by Rexogamer** [comment]
okay

**Comment by Rexogamer** [comment]
please note this means that config will ceas to exist and everything would be separate imports, but I guess that’s the point (eg `import { colors, links } from '../config'`

**Comment by Mitchell3514** [comment]
Import should specify a name: 
```
import * as config from "../config"
```

**Comment by Rexogamer** [comment]
importing * just imports everything

**Comment by Rexogamer** [comment]
also tbh I don’t see the point of this particular import as we can just import the parts of the config where we need it

**Comment by Mitchell3514** [comment]
You can only `import *` by giving it a variable, so you do need `as name`.

**Comment by Rexogamer** [comment]
Oh sorry, I misunderstood you. I’ll remove the import anyway as it doesn’t seem to be used in that file.

**Comment by Mitchell3514** [comment]
Thanks

**Pull request merged**
