### PR TITLE
GReek Guide translation

### PR DESCRIPTION
**Pull request by babdab9**
**PLEASE DO NOT MERGE UNTIL I SAY THEY ARE FINISHED**

### CODE REVIEW

**Comment by babdab9** [comment]
NO

**Comment by Keanu73** [comment]
?

**Comment by babdab9** [comment]
@Keanu73 Tempestus knows 😏

**Comment by Keanu73** [comment]
"Tempestus"
It's Tempestius you dingus

**Comment by babdab9** [comment]
Made a mistake dammit! Lets move to discord tho ;P

**Comment by babdab9** [comment]
you can merge :) done for today

**Comment by austinhuang0131** [comment]
> PLEASE DO NOT MERGE UNTIL I SAY THEY ARE FINISHED

aren't u supposed to make a pr when u finish

**Comment by Keanu73** [comment]
This doesn't look finished.. where's the images? Also please translate everything.

**Comment by babdab9** [comment]
when I have time :joy:

**Pull request closed without merging**
