### PR TITLE
Fixed handler, eslinted code, added ping, ignored node_modules, other misc changes.

### PR DESCRIPTION
**Pull request by SunburntRock89**

### CODE REVIEW

**Comment by austinhuang0131** [comment]
gh's not letting me merge

**Comment by Keanu73** [comment]
austin this is because you need to define the variables

**Comment by Keanu73** [comment]
in the rewrite

**Comment by SunburntRock89** [comment]
there's also conflicts

**Comment by SunburntRock89** [comment]
let me fix a few things

**Comment by austinhuang0131** [comment]
^ Manually merged everything above this point

**Comment by austinhuang0131** [comment]
wait no

**Comment by SunburntRock89** [comment]
uh, what up?

**Comment by SunburntRock89** [comment]
oh right you accidentally committed to master

**Comment by austinhuang0131** [comment]
can't merge. i guess i'll download ur repo and force it to merge

**Comment by SunburntRock89** [comment]
there's a button that says make changes in github desktop or do it from the command line

**Comment by austinhuang0131** [comment]
i tried gh desktop and it just doesn't work

**Comment by SunburntRock89** [comment]
oh right

**Comment by SunburntRock89** [comment]
I've had that work in the past

**Comment by austinhuang0131** [comment]
ok i have to download ur repo and merge it

also we actually have eslint on codacy

**Comment by SunburntRock89** [comment]
oh lol

**Comment by SunburntRock89** [comment]
austin you do realise it just went to mergable

**Pull request closed without merging**
