### PR TITLE
add eval command

### PR DESCRIPTION
**Pull request by NubbyTM**
I noticed that you guys didn't have an eval command, so I made it for you. Only people with the eval role may run evaluations, and protections are added to make sure no one can find the bot's token.

nubbytm

### CODE REVIEW

**Comment by austinhuang0131** [comment]
responses are not funny but i'll make them funnier

**Comment by Keanu73** [comment]
thats Boring

**Comment by Keanu73** [comment]
we need a spicy embed eval

**Comment by NubbyTM** [comment]
keanu you cant use codeblocks in embeds.

**Comment by Keanu73** [comment]
yes you can dingus
you can escape the characters lol

**Comment by Keanu73** [comment]
Uhh yeah you can lol

**Comment by Keanu73** [comment]
dingus

**Comment by Keanu73** [comment]
you just gotta escape the backticks

**Comment by austinhuang0131** [comment]
what the fuck why do u delete your previous comment and make that into 3 fucking comments u dingus

**Comment by Keanu73** [comment]
i thought you couldnt put codeblocks in embeds but i looked into my old selfbot usage and i saw that i did so i was right all along dingus

**Pull request merged**
